workflows:
  native-android:
    name: Native Android
    #instance_type: windows_x2
    environment:
      groups:
        - keystore_credentials <keystore,Rise@123,key0>
      vars:
        CM_KEYSTORE_PATH: keystore.jks
        node: latest
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: true
    scripts:

      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > keystore.keystore

    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - pavan.yegi@gmail.com
          - pavan.y@prostem.org
        notify:
          success: true
          failure: false
        #pavangoogle_play:                          # For publishing your Android app to Google Play
        #pavan credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        #pavan track: alpha                      # Name of the track: internal, alpha, beta, production